#!/usr/bin/env python3
"""Run the real-runtime compatibility matrix and publish the results.

    scripts/compat_matrix.py [--runtime NAME] [--write-baselines] [--docs-only]

For every runtime below, over both provider protocols and with and without
streaming, this runs `boundarycheck run --extended --probes` and writes:

  * target/compat/<runtime>-<protocol>[-stream].json   (the reports)
  * docs/compatibility.md                              (the published table)
  * with --write-baselines: adapters/<dir>/expected*.json, keeping existing
    "why" explanations (new non-PASS entries get "why": "UNEXPLAINED", which
    must be replaced by hand before committing).

Runtimes are installed from their hash-locked requirements into
target/compat-venvs/. The results are facts about what reached the provider,
not rankings.
"""

import argparse
import datetime
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

RUNTIMES = [
    {"name": "openai-agents", "dir": "openai-agents-python", "adapter": "openai-agents-python",
     "responses_flag": ["--responses"]},
    {"name": "pydantic-ai", "dir": "pydantic-ai-python", "adapter": "pydantic-ai-python",
     "responses_flag": ["--responses"]},
    {"name": "langgraph", "dir": "langgraph-python", "adapter": "langgraph-python",
     "responses_flag": ["--responses"]},
]
PROTOCOLS = [("openai-chat-completions", "", "expected.json"), ("openai-responses", "-responses", "expected-responses.json")]
MODES = [("", []), ("-stream", ["--stream"])]


def run(cmd, **kw):
    return subprocess.run(cmd, cwd=ROOT, **kw)


def venv_python(rt, venvs):
    venv = venvs / rt["name"]
    python = venv / "bin" / "python"
    if not python.exists():
        print(f"installing {rt['name']} from its lock file", file=sys.stderr)
        run([sys.executable, "-m", "venv", str(venv)], check=True)
        run([str(python), "-m", "pip", "install", "-q", "--require-hashes", "--no-deps", "-r",
             f"adapters/{rt['dir']}/requirements.lock"], check=True)
        run([str(python), "-m", "pip", "check"], check=True)
    return python


def report_path(out, rt, suffix, mode):
    return out / f"{rt['name']}{suffix or '-chat'}{mode}.json"


def cell(s):
    v = s["verdict"]
    return f"{v} {', '.join(s['classifications'])}" if v == "FAIL" else v


def short_note(n):
    # "BC_CALL_000001 (request #2): text" -> "text"
    return n.split("): ", 1)[1] if n.startswith("BC_CALL_") and "): " in n else n


def write_docs(out, bc_version, commit):
    columns, reports = [], {}
    for rt in RUNTIMES:
        for proto, suffix, _ in PROTOCOLS:
            normal = report_path(out, rt, suffix, "")
            stream = report_path(out, rt, suffix, "-stream")
            if normal.exists():
                columns.append((rt, proto))
                reports[(rt["name"], proto)] = (json.load(open(normal)),
                                                json.load(open(stream)) if stream.exists() else None)
    if not columns:
        sys.exit("no reports found; run without --docs-only first")
    scenario_ids = []
    for normal, _ in reports.values():
        scenario_ids += [s["id"] for s in normal["scenarios"] if s["id"] not in scenario_ids]
    lines = [
        "# Compatibility data",
        "",
        f"Generated by `scripts/compat_matrix.py` on {datetime.date.today().isoformat()} with boundarycheck "
        f"{bc_version} (commit `{commit}`). Every runtime is installed from its hash-locked "
        "`adapters/<runtime>/requirements.lock` and runs unmodified behind a thin adapter script.",
        "",
        "These are facts about what reached the model provider, not rankings. FAIL means the provider-visible "
        "content differed from what the MCP server emitted under the rules in the README "
        "([MCP content](../README.md#mcp-content)); UNKNOWN means the harness could not prove either way "
        "(for example, the runtime exited, or the content cannot be carried by the protocol). "
        "Explanations for every non-PASS entry are below the table.",
        "",
        "## Runtimes",
        "",
        "| Runtime | Version | Pinned dependencies |",
        "|---|---|---|",
    ]
    seen = set()
    for rt, proto in columns:
        if rt["name"] in seen:
            continue
        seen.add(rt["name"])
        info = reports[(rt["name"], proto)][0]["runtime"]
        details = info.get("details") or {}
        deps = ", ".join(f"{k} {v}" for k, v in details.items() if k not in ("name", "version") and v)
        lines.append(f"| {rt['name']} | {info.get('version')} | {deps} |")
    head = "| Scenario | " + " | ".join(f"{rt['name']}<br>{'Chat' if 'chat' in p else 'Responses'}" for rt, p in columns) + " |"
    lines += ["", "## Results", "", "Cells read `non-streaming / streaming` when the two differ.", "", head,
              "|---|" + "---|" * len(columns)]
    for sid in scenario_ids:
        row = [f"`{sid}`"]
        for rt, proto in columns:
            normal, stream = reports[(rt["name"], proto)]
            a = next((s for s in normal["scenarios"] if s["id"] == sid), None)
            if a is None:
                row.append("not run¹")
                continue
            b = next((s for s in stream["scenarios"] if s["id"] == sid), None) if stream else None
            c = cell(a)
            row.append(c if b is None or cell(b) == c else f"{c} / {cell(b)}")
        lines.append("| " + " | ".join(row) + " |")
    lines += ["", "¹ The adapter does not declare the lifecycle capability the scenario needs "
              "(`history-replay` or `persistence-resume`), so the scenario is omitted.", "", "## Explanations", ""]
    for rt in RUNTIMES:
        for proto, suffix, baseline in PROTOCOLS:
            path = ROOT / "adapters" / rt["dir"] / baseline
            if not path.exists():
                continue
            entries = json.load(open(path))["scenarios"]
            items = []
            for sid, e in entries.items():
                if e.get("why"):
                    items.append(f"- `{sid}` ({e['verdict']}): {e['why']}")
                if "stream" in e:
                    items.append(f"- `{sid}` with streaming ({e['stream']['verdict']}): {e['stream']['why']}")
            if items:
                lines += [f"**{rt['name']}, {'Chat Completions' if suffix == '' else 'Responses'}**", ""] + items + [""]
    lines += ["## Notes", "",
              "Legal representation choices and other observations, reported as notes on PASS results:", ""]
    for rt in RUNTIMES:
        notes = set()
        for proto, suffix, _ in PROTOCOLS:
            for rep in reports.get((rt["name"], proto), (None, None)):
                for s in (rep or {}).get("scenarios", []):
                    notes.update(f"`{s['id']}`: {short_note(n)}" for n in s["notes"]
                                 if "legal reordering" not in n)
        if notes:
            lines += [f"**{rt['name']}**", ""] + [f"- {n}" for n in sorted(notes)] + [""]
    (ROOT / "docs" / "compatibility.md").write_text("\n".join(lines).rstrip() + "\n")
    print("wrote docs/compatibility.md")


def write_baselines(out):
    for rt in RUNTIMES:
        for proto, suffix, baseline in PROTOCOLS:
            normal, stream = report_path(out, rt, suffix, ""), report_path(out, rt, suffix, "-stream")
            if not normal.exists():
                continue
            path = ROOT / "adapters" / rt["dir"] / baseline
            old = json.load(open(path))["scenarios"] if path.exists() else {}
            n = json.load(open(normal))
            s = {x["id"]: x for x in json.load(open(stream))["scenarios"]} if stream.exists() else {}
            entries = {}
            for sc in n["scenarios"]:
                sid, prev = sc["id"], old.get(sc["id"], {})
                e = {"verdict": sc["verdict"]}
                if sc["verdict"] == "FAIL":
                    e["classifications"] = sc["classifications"]
                if sc["verdict"] != "PASS":
                    e["why"] = prev.get("why", "UNEXPLAINED")
                st = s.get(sid)
                if st and st["verdict"] != sc["verdict"]:
                    e["stream"] = {"verdict": st["verdict"],
                                   "why": prev.get("stream", {}).get("why", "UNEXPLAINED")}
                    if st["verdict"] == "FAIL":
                        e["stream"]["classifications"] = st["classifications"]
                if e != {"verdict": "PASS"}:
                    entries[sid] = e
            doc = {"runtime": n["runtime"].get("name"), "version": n["runtime"].get("version"),
                   "protocol": proto, "default_verdict": "PASS", "scenarios": entries}
            path.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
            print(f"wrote {path.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runtime", action="append", help="limit to these runtime names")
    ap.add_argument("--bc", default=str(ROOT / "target/release/boundarycheck"))
    ap.add_argument("--venvs", default=str(ROOT / "target/compat-venvs"))
    ap.add_argument("--out", default=str(ROOT / "target/compat"))
    ap.add_argument("--write-baselines", action="store_true")
    ap.add_argument("--docs-only", action="store_true")
    args = ap.parse_args()
    out, venvs = Path(args.out), Path(args.venvs)
    out.mkdir(parents=True, exist_ok=True)
    venvs.mkdir(parents=True, exist_ok=True)
    selected = [rt for rt in RUNTIMES if not args.runtime or rt["name"] in args.runtime]
    if not args.docs_only:
        for rt in selected:
            python = venv_python(rt, venvs)
            for proto, suffix, _ in PROTOCOLS:
                for mode, mode_flags in MODES:
                    flags = (rt["responses_flag"] if suffix else []) + mode_flags
                    report = report_path(out, rt, suffix, mode)
                    print(f"== {rt['name']} {proto} {' '.join(mode_flags) or '(no streaming)'}", file=sys.stderr)
                    r = run([args.bc, "run", "--adapter", rt["adapter"] + suffix, "--extended", "--probes",
                             "--report", str(report), "--", str(python), f"adapters/{rt['dir']}/agent.py", *flags],
                            stdout=subprocess.DEVNULL)
                    if r.returncode == 2:
                        sys.exit(f"harness error for {rt['name']} {proto}{mode}; see {report}")
    if args.write_baselines:
        write_baselines(out)
    version = run([args.bc, "--version"], capture_output=True, text=True).stdout.split()[-1]
    commit = run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip() or "unknown"
    write_docs(out, version, commit)


if __name__ == "__main__":
    main()
